stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/loan_approval.csv
    outs:
      - data/train.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/train.csv
    outs:
      - models/random_forest.pkl

  tune:
    cmd: python tune.py
    deps:
      - tune.py
      - data/train.csv
    outs:
      - models/best_model.pkl
